# Generated by Django 4.1.1 on 2022-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("AnimeName", models.CharField(max_length=255)),
                ("Gogoanime_url", models.CharField(max_length=255)),
                ("Gogoanime_Id", models.IntegerField()),
                ("No_of_Episodes", models.IntegerField()),
                (
                    "Status",
                    models.CharField(
                        choices=[(False, "Draft"), (True, "Published")], max_length=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
