# Generated by Django 4.1.1 on 2022-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gogoanime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anime_All",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("anime_name", models.CharField(max_length=255)),
                ("gogoanime_url", models.CharField(max_length=255, unique=True)),
                ("gogoanime_id", models.IntegerField(unique=True)),
                ("no_of_episodes", models.IntegerField()),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Complete", "Complete"),
                            ("Ongoing", "Ongoing"),
                            ("Upcoming", "Upcoming"),
                        ],
                        max_length=20,
                    ),
                ),
                ("other_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AnimeInfo",
        ),
    ]
