# Generated by Django 4.1.1 on 2022-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gogoanime", "0002_anime_all_delete_animeinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime_all",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/anime_img"),
        ),
    ]
