# Generated by Django 4.1.1 on 2023-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gogoanime", "0004_remove_anime_all_other_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime_all",
            name="image",
            field=models.ImageField(blank=True, upload_to="anime_img/"),
        ),
    ]
